from __future__ import annotations


class Balance:
    DAY_S = 86400.0
    YEAR_S = 365.0 * DAY_S
    HIBERNATE_CHUNK_S = 7 * DAY_S
    HIBERNATE_WAKE_CHECK_S = 1 * 60 * 60
    HIBERNATE_WAKE_EVENT_TYPES = {"drone_low_battery"}

    # Power/alerts
    BUS_INSTABILITY_AFTER_S = 120
    LOW_POWER_QUALITY_THRESHOLD = 0.7
    R_REF = 0.05

    # Job times (seconds)
    REPAIR_TIME_S = 25.0
    DEPLOY_TIME_S = 13.0
    REBOOT_TIME_S = 15.0
    RECALL_TIME_S = 10.0
    DOCK_TIME_S = 12.0
    INSTALL_TIME_S = 30.0
    SALVAGE_SCRAP_BASE_S = 4.0
    SALVAGE_SCRAP_PER_UNIT_S = 1.5
    SALVAGE_MODULE_TIME_S = 12.0
    SALVAGE_DATA_TIME_S = 18.0
    SELFTEST_REPAIR_TIME_S = 18.0
    SELFTEST_REPAIR_AMOUNT = 0.05
    REPAIR_SCRAP_PER_HEALTH = 20
    SELFTEST_REPAIR_SCRAP_PER_HEALTH = 12
    CARGO_AUDIT_TIME_S = 11.0

    # Transit wear / warnings
    TRANSIT_WEAR_MULT_NORMAL = 2.5
    TRANSIT_WARN_YEARS = 0.2

    # Emergency deploy risk (per second)
    EMERGENCY_DEPLOY_P_FAIL_PER_S = 0.03
    EMERGENCY_DEPLOY_P_GLITCH_PER_S = 0.05

    # Drone recall/reboot success probability clamps
    DRONE_REBOOT_P_MIN = 0.2
    DRONE_REBOOT_P_MAX = 0.9
    DRONE_RECALL_P_MIN = 0.3
    DRONE_RECALL_P_MAX = 0.95
    DRONE_RECALL_MIN_INTEGRITY = 0.10
    DRONE_DEPLOY_MIN_INTEGRITY = 0.10
    DRONE_MOVE_MIN_INTEGRITY = 0.10

    # Salvage probabilities
    SALVAGE_SCRAP_FIND_MODULE_P = 0.10
    SALVAGE_MODULE_FIND_P = 0.75
    SALVAGE_DATA_LOG_P_STATION_SHIP = 0.70
    SALVAGE_DATA_LOG_P_OTHER = 0.50
    SALVAGE_DATA_MAIL_P_STATION_SHIP = 0.50
    SALVAGE_DATA_MAIL_P_OTHER = 0.30
    SALVAGE_DATA_FRAG_P_STATION_DERELICT = 0.25
    SALVAGE_DATA_FRAG_P_OTHER = 0.15

    # System health thresholds
    SYSTEM_HEALTH_OFFLINE = 0.0
    SYSTEM_HEALTH_CRITICAL = 0.35
    SYSTEM_HEALTH_DAMAGED = 0.60
    SYSTEM_HEALTH_LIMITED = 0.85
    SYSTEM_HEALTH_MIN_ON = 0.0

    # Power core output multipliers by state
    POWER_CORE_MULT_OFFLINE = 0.0
    POWER_CORE_MULT_CRITICAL = 0.25
    POWER_CORE_MULT_DAMAGED = 0.50
    POWER_CORE_MULT_LIMITED = 0.75
    POWER_CORE_MULT_NOMINAL = 1.0

    # Sensors
    SENSORS_RANGE_LY = 2.5
    SENSORS_DETECT_P_NEAR = 0.95
    SENSORS_DETECT_P_FAR = 0.30
    SENSORS_DETECT_P_NOMINAL = 1.00
    SENSORS_DETECT_P_LIMITED = 0.85
    SENSORS_DETECT_P_DAMAGED = 0.60
    SENSORS_DETECT_P_CRITICAL = 0.35

    # Route solving
    ROUTE_SOLVE_MIN_S = 100.0
    ROUTE_SOLVE_MAX_S = 1800.0

    # Drone battery/integrity maintenance
    DRONE_BATTERY_DRAIN_DEPLOY = 0.06
    DRONE_BATTERY_DRAIN_RECALL = 0.05
    DRONE_BATTERY_DRAIN_REPAIR = 0.08
    DRONE_BATTERY_DRAIN_SALVAGE = 0.07
    DRONE_BATTERY_DRAIN_REBOOT = 0.04
    DRONE_BATTERY_DRAIN_SELFTEST = 0.02
    DRONE_BATTERY_DRAIN_MOVE = 0.05
    DRONE_BATTERY_CHARGE_PER_S = 0.02
    DRONE_BATTERY_CHARGE_LOW_MULT = 0.25
    DRONE_CHARGE_KW = 0.2
    DRONE_CHARGE_NET_MIN_KW = -0.2
    DRONE_BATTERY_IDLE_DRAIN_DEPLOYED_PER_S = 0.00002 # Velocidad a la que descarga sin hacer nada
    DRONE_REPAIR_INTEGRITY_PER_SCRAP = 0.02
    DRONE_LOW_BATTERY_THRESHOLD = 0.15
    DRONE_MIN_BATTERY_FOR_TASK = 0.10
    DRONE_MIN_BATTERY_FOR_RECALL = 0.05

    # Bootstrap node salvage (ECHO_7)
    # ECHO_7_SCRAP_MIN = 50
    # ECHO_7_SCRAP_MAX = 70
    # ECHO_7_MODULES_MIN = 0
    # ECHO_7_MODULES_MAX = 2
